### ISSUE TITLE
super method error

### ISSUE THREAD

**Issue by quanvn** [dr-itz/redmine_workflow_enhancements#7]
when edit workflow or tracker  I got this error 

      ':super' is not an ActiveModel-compatible object that returns a valid partial path .

 I use redmine 2.6.6, ruby 2, rails 3.2.22. Could you check this problem?

**Comment by dr-itz** [comment]
Please provide the following info:
* Output of Redmine's Info page (Administration -> Info)
* Log with the error, including the stack trace

**Comment by quanvn** [comment]
I found out that the problem is due to the conflict with gem haml (used by redmine_dashboard and redmine_related_buster). Removing the two plugins use haml solves the problem. 

I still cannot see the graph and click on the ? in issue edit give the loading icon, but could not open anything. But I guess that this is due my browser.

So if you have time, please check if this plugin could work with haml?

**Comment by dr-itz** [comment]
Thanks for tracking this down to a conflict with haml. I'll have a look.

**Comment by dr-itz** [comment]
Just pushed a fix for it. Please pull and test.

**Comment by quanvn** [comment]
I confirm the fix works. (I still could not see the graph in any ie, firefox, chrome). But this is probably due to browser setting. I will try to tweak them later. Thanks Daniel for your quick fix.

**Comment by dr-itz** [comment]
Thanks for testing. No idea why you're not seeing the graph. Does Redmine's log file say anything? Or the browser console? It might be some javascript problem.

**Comment by quanvn** [comment]
Thank you for reminding me that. There is no error with redmine log (render complete with 200 OK) but the console show this error 

Error: Node '5' is not in graph dagre-d3.min.js:2:3652

and here is the log info of my data (this is when I edit workflow)

TRACKERS: [#<Tracker id: 3, name: "Ke Hoach", is_in_chlog: false, position: 2, is_in_roadmap: false, fields_bits: 68>].
ROLES: [#<Role id: 3, name: "Lanh Dao", position: 2, assignable: true, builtin: 0, permissions: [...].
ISSUE: nil

**Comment by dr-itz** [comment]
Glad it works :) Thank you.
