### ISSUE TITLE
No plugin config pages

### ISSUE THREAD

**Issue by igor-panassiouk** [dr-itz/redmine_workflow_enhancements#8]
There is a question sign near issue status and workflow "picture" under it.

But no "workflow" or "Tracker" under "Administration".

Redmine 2.3.0

**Comment by dr-itz** [comment]
Hmm..just tested with Redmine 2.3.4. Works for me. Maybe a silly questions, but...In Administration -> Tracker, did you actually click on a tracker? Same in Administration -> Workflow: select role/tracker, press "Edit". If so:
* Do you have other plugins installed
* What's your exact environment (Administration -> Information)

**Comment by igor-panassiouk** [comment]
1. Sorry, I was wrong about "Tracker" submenu - it exists...
But when I click on any tracker - "Internal error. An error occurred on the page you were trying to access."

**Production.log entry (partial):**
" Rendered plugins/redmine_workflow_enhancements/app/views/trackers/edit.html.erb within layouts/admin (3.6ms)
Completed 500 Internal Server Error in 27ms

ActionView::Template::Error (':super' is not an ActiveModel-compatible object that returns a valid partial path.):
    1: <%= render :super %>
    2:
    3: <div class="workflowGraphContainer">
    4:   <%= render :partial => 'workflow_enhancements/workflow_graph', :locals => {
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:385:in `partial_path'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:295:in `setup'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:221:in `render'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.13) lib/action_view/helpers/rendering_helper.rb:27:in `render'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  plugins/redmine_workflow_enhancements/app/views/trackers/edit.html.erb:1:in `_85f2d25696a1e1842baec92f549f8ed9'

**2. "Workflow" entry is absent** under "Administration" - may be because of "Custom workflows" plugin
I have many plugins (may too much)

**3. System Info:**
Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2

**Comment by dr-itz** [comment]
Thanks for the info. It's now the same problem as in #7. On it, but might take a while.

**Comment by dr-itz** [comment]
Spoke too soon...turned out to be easier than expected. Just pushed a fix for it. Please pull and test.
That should at least fix the problem in "Trackers"...

**Comment by igor-panassiouk** [comment]
Patch solver "Trackers" submenu error.
"Workflow" submenu is still absent under "Administration" in my installation

**Comment by dr-itz** [comment]
Thanks for testing. Well if the menu entry "Workflow" does not exists to start with, it's probably some other plugin that messes with that. redmine_workflow_enhancements only overrides the workflow edit view, but not the admin menu or any controller.
