### ISSUE TITLE
how the association between tracker and status should work

### ISSUE THREAD

**Issue by quanvn** [dr-itz/redmine_workflow_enhancements#9]
I don't understand very well your intention about how the association between a tracker and the status should work. I think that this should place a restriction (maybe this is not your intention). But currently, it seems that this has no effect since I always see all the status even if I select only one status in the tracker editing screen

**Comment by dr-itz** [comment]
The idea is to control what's showed in "workflow" -> "status transitions" -> "edit". When you have a lot of different statuses and create a new tracker, things get messy. The default is to only show statuses that are included in the workflow ("Only display statuses that are used by this tracker" checked). With a new tracker there are none. Unchecking said checkbox displays all statuses which makes it hard to find the ones you care about.

The plugin solves this with the pre-defined association in the tracker. It changes the behavior when "Only display statuses that are used by this tracker" is checked. It will display all statuses involved in the actual workflow (normal behavior) but also includes all the pre-defined ones. The behavior with that checkbox unchecked is unchanged, it will display all the statuses.

Hope that explains it :)

**Comment by quanvn** [comment]
Thank you very much for clear explanation. Now I understand how to use this feature :-). Best wishes to you.

**Comment by dr-itz** [comment]
Thank you for your feedback. It's much appreciated. I updated the README to explain things better.
